### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 650113: invalid continuation byte

### ISSUE THREAD

**Issue by olleharstedt** [flacle/truegitcodechurn#23]
Getting this error on my latest run:

Traceback (most recent call last):
  File "/truegitcodechurn/./gitcodechurn.py", line 264, in <module>
    main()
  File "/truegitcodechurn/./gitcodechurn.py", line 94, in main
    [files, contribution, churn] = get_loc(
  File "/truegitcodechurn/./gitcodechurn.py", line 121, in get_loc
    results = get_proc_out(command, dir).splitlines()
  File "/truegitcodechurn/./gitcodechurn.py", line 247, in get_proc_out
    return process.communicate()[0].decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 650113: invalid continuation byte

**Comment by pechezerov** [comment]
It's working for me
247: `return process.communicate()[0].decode("latin-1")`
